// Convenient aliases over the auto-generated OpenAPI types.
// schema.ts is generated by `npm run gen:api` (from docs/02_api_openapi.yaml) —
// do not edit it by hand. Import these aliases in app code.
import type { components } from "./schema";

export type Coordinates = components["schemas"]["Coordinates"];
export type AskRequest = components["schemas"]["AskRequest"];
// POST /ask-audio: the same question, recorded. Sent as multipart/form-data,
// so `audio` is the file itself rather than a field to assign a string to.
export type AskAudioRequest = components["schemas"]["AskAudioRequest"];
// POST /ask only accepts the question; the answer comes from GET /ask/{id}.
export type AskAcceptedResponse = components["schemas"]["AskAcceptedResponse"];
export type AskResultResponse = components["schemas"]["AskResultResponse"];
export type HealthResponse = components["schemas"]["HealthResponse"];
